name: Deploy serverless and unit testing for main environments.

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read


jobs:
  integration-testing:
    if: github.ref_name == 'main'
    name: Integration testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_GITHUB_ACTIONS }}
        aws-region: ${{ secrets.IAM_ROLE_REGION }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node dependencies
      run: npm ci

    - name: serverless deploy integration-testing
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage integration-testing

    - name: Output API URL
      run: cat .env

    - name: Integration testing
      run: npm run integration-test

    - name: serverless remove integration-testing
      if: ${{ always() }}
      uses: serverless/github-action@v3.1
      with:
        args: remove --stage integration-testing

  deploy:
    needs: integration-testing
    if: ${{ success () || always() }}
    name: Serverless deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: fail if integration-test fails
      if: ${{ needs.integration-testing.result == 'failure' }}
      run: exit 1

    - name: Get code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_GITHUB_ACTIONS }}
        aws-region: ${{ secrets.IAM_ROLE_REGION }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node dependencies
      run: npm ci

    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage ${{ github.ref_name }}

    - name: Output API URL
      run: cat .env
