name: Pull-request validation

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node dependencies
      run: npm ci

    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        file: serverless.yml # optional: provide the path for resource to be scanned. This will override the directory if both are provided.
        framework: serverless # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
        skip_check: CKV_AWS_119

    - name: Run NodeJS Linters/Security Checks
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        eslint_dir: lambdas/

  testing:
    needs: lint
    name: Unit testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node dependencies
      run: npm ci

    - name: unit tests
      uses: serverless/github-action@v3.1
      with:
        args: invoke test
